[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
extra_scripts = pre:../Shared/load_env.py
build_flags = 
	-I../Shared
lib_deps = 
	knolleary/PubSubClient@^2.8
	madhephaestus/ESP32Servo@^3.0.6
	miguelbalboa/MFRC522@^1.4.11
	bblanchon/ArduinoJson@^7.0.4
