[platformio]
default_envs = hfr-s16

[env]
platform = espressif32@6.10.0
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags =
    --before=no_reset
    --after=no_reset
board_build.partitions = partitions.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I../Shared
    -I../ESP32-Automatic-Gate/include

[env:hfr-s16]
build_flags =
    ${env.build_flags}
    -DHFR_QUANT_S16=1

[env:hfr-s8]
build_flags =
    ${env.build_flags}
    -DHFR_QUANT_S16=0
