[env:esp32cam-stream]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-A5069RR4
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
monitor_rts = 0
monitor_dtr = 0
extra_scripts = pre:../Shared/load_env.py
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-I../Shared
