[platformio]
default_envs = esp32cam_node, esp32_main_controller
src_dir = src/hardware

[env]
platform = espressif32
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.flash_mode = dio
monitor_filters = esp32_exception_decoder

; Uncomment and adjust these if PlatformIO auto-detects the wrong serial port.
; upload_port = COM3
; monitor_port = COM3

[env:esp32cam_node]
board = esp32cam
build_src_filter =
  -<*>
  +<platformio_esp32cam_node.cpp>

[env:esp32_main_controller]
board = esp32dev
build_src_filter =
  -<*>
  +<platformio_main_controller.cpp>
lib_deps =
  madhephaestus/ESP32Servo@^3.0.6
